language: java
jdk:
- oraclejdk8

deploy:
	skip_cleanup: true

  provider: releases
  api_key: 
    secure: $GITHUB_SECURE_TOKEN
  file: '$TRAVIS_BUILD_DIR/libs/service-synology-chatbot-*.jar'
  on:
    repo: antoine-aumjaud/api-syno-chatbot
